### ISSUE TITLE
SSH authorization

### ISSUE THREAD

**Issue by pearsonhenri** [terraform-module/terraform-aws-proxy-sqlserver#1]
## Support Question

Hi there! Just stumbled across this module--it looks super useful and I'm looking forward to using it! One thing I'm unable to figure out is how to properly configure the SSH allowed keys so I can ssh to an instance. Sorry if I'm a bit of a noob here--not much experience with cloud init config!

A question I had though was if we could just use the standard AWS .pem key to handle SSH security for the instance. Would be happy to contribute a change to this module to use that instead.

Thanks!

**Comment by ivankatliarchuk** [comment]
Pardon just realized there is an issue.
```
ssh_authorized_key = "ssh-rsa AAAA mykey@host"
```

just replace `AAA` with your key. Feel free to make any require PR
